/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LiveTrackRouteImport } from './routes/live-track'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PassengerRouteImport } from './routes/passenger'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PersonalInfoRouteImport } from './routes/personal-info'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SeatsRouteImport } from './routes/seats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as WalletRouteImport } from './routes/wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTrackRoute = LiveTrackRouteImport.update({
  id: '/live-track',
  path: '/live-track',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRoute = PassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalInfoRoute = PersonalInfoRouteImport.update({
  id: '/personal-info',
  path: '/personal-info',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatsRoute = SeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/live-track': typeof LiveTrackRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/passenger': typeof PassengerRoute
  '/payment': typeof PaymentRoute
  '/personal-info': typeof PersonalInfoRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/search': typeof SearchRoute
  '/seats': typeof SeatsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/ticket': typeof TicketRoute
  '/tickets': typeof TicketsRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/live-track': typeof LiveTrackRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/passenger': typeof PassengerRoute
  '/payment': typeof PaymentRoute
  '/personal-info': typeof PersonalInfoRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/search': typeof SearchRoute
  '/seats': typeof SeatsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/ticket': typeof TicketRoute
  '/tickets': typeof TicketsRoute
  '/wallet': typeof WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/live-track': typeof LiveTrackRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/passenger': typeof PassengerRoute
  '/payment': typeof PaymentRoute
  '/personal-info': typeof PersonalInfoRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/search': typeof SearchRoute
  '/seats': typeof SeatsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/ticket': typeof TicketRoute
  '/tickets': typeof TicketsRoute
  '/wallet': typeof WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/home'
    | '/live-track'
    | '/notifications'
    | '/offers'
    | '/onboarding'
    | '/passenger'
    | '/payment'
    | '/personal-info'
    | '/privacy'
    | '/profile'
    | '/refer'
    | '/search'
    | '/seats'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/ticket'
    | '/tickets'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/home'
    | '/live-track'
    | '/notifications'
    | '/offers'
    | '/onboarding'
    | '/passenger'
    | '/payment'
    | '/personal-info'
    | '/privacy'
    | '/profile'
    | '/refer'
    | '/search'
    | '/seats'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/ticket'
    | '/tickets'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/home'
    | '/live-track'
    | '/notifications'
    | '/offers'
    | '/onboarding'
    | '/passenger'
    | '/payment'
    | '/personal-info'
    | '/privacy'
    | '/profile'
    | '/refer'
    | '/search'
    | '/seats'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/ticket'
    | '/tickets'
    | '/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  LiveTrackRoute: typeof LiveTrackRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  OnboardingRoute: typeof OnboardingRoute
  PassengerRoute: typeof PassengerRoute
  PaymentRoute: typeof PaymentRoute
  PersonalInfoRoute: typeof PersonalInfoRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReferRoute: typeof ReferRoute
  SearchRoute: typeof SearchRoute
  SeatsRoute: typeof SeatsRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TicketRoute: typeof TicketRoute
  TicketsRoute: typeof TicketsRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-track': {
      id: '/live-track'
      path: '/live-track'
      fullPath: '/live-track'
      preLoaderRoute: typeof LiveTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger': {
      id: '/passenger'
      path: '/passenger'
      fullPath: '/passenger'
      preLoaderRoute: typeof PassengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-info': {
      id: '/personal-info'
      path: '/personal-info'
      fullPath: '/personal-info'
      preLoaderRoute: typeof PersonalInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seats': {
      id: '/seats'
      path: '/seats'
      fullPath: '/seats'
      preLoaderRoute: typeof SeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  LiveTrackRoute: LiveTrackRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  OnboardingRoute: OnboardingRoute,
  PassengerRoute: PassengerRoute,
  PaymentRoute: PaymentRoute,
  PersonalInfoRoute: PersonalInfoRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReferRoute: ReferRoute,
  SearchRoute: SearchRoute,
  SeatsRoute: SeatsRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TicketRoute: TicketRoute,
  TicketsRoute: TicketsRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
